/**
 * FALLBACK CATALOG — guaranteed-working royalty-free tracks.
 *
 * Used when both Audius and Jamendo return empty results (rate limits, CORS,
 * or network failure). All audio URLs are publicly accessible MP3s that work
 * without authentication or special headers from a browser.
 *
 * Sources:
 *  - Audio: SoundHelix.com (royalty-free, no CORS restrictions)
 *  - Art:   Unsplash Source API (royalty-free, CORS open, dynamic crop)
 */
import type { Track, Artist } from "./types";

const makeArt = (query: string, seed: number) =>
  `https://picsum.photos/seed/${seed}/500/500`;

const makeAudiusCover = (id: string) =>
  `https://usermetadata.audius.co/content/${id}/cover_art_sizes/150x150.jpg`;

// 20 curated fallback tracks
export const FALLBACK_TRACKS: Track[] = [
  {
    id: "fallback-1",
    title: "Synth Odyssey",
    artistId: "fallback-artist-1",
    artistName: "SoundHelix Collective",
    coverImage: makeArt("electronic synth", 101),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    duration: 371,
    genre: "Electronic",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 12400,
    likes: 890,
    comments: 45,
    createdAt: "2025-03-10",
  },
  {
    id: "fallback-2",
    title: "Midnight Drive",
    artistId: "fallback-artist-1",
    artistName: "SoundHelix Collective",
    coverImage: makeArt("night city drive", 102),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    duration: 337,
    genre: "Ambient",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 9800,
    likes: 670,
    comments: 28,
    createdAt: "2025-03-11",
  },
  {
    id: "fallback-3",
    title: "Urban Pulse",
    artistId: "fallback-artist-2",
    artistName: "Neon Architects",
    coverImage: makeArt("urban neon city", 103),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    duration: 342,
    genre: "Hip-Hop",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 8200,
    likes: 560,
    comments: 31,
    createdAt: "2025-03-12",
  },
  {
    id: "fallback-4",
    title: "Crystal Waters",
    artistId: "fallback-artist-3",
    artistName: "Aqua Tones",
    coverImage: makeArt("crystal blue water", 104),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    duration: 398,
    genre: "Ambient",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 7100,
    likes: 520,
    comments: 19,
    createdAt: "2025-03-15",
  },
  {
    id: "fallback-5",
    title: "Rock Anthem",
    artistId: "fallback-artist-4",
    artistName: "Electric Storm",
    coverImage: makeArt("rock guitar concert", 105),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    duration: 356,
    genre: "Rock",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 15600,
    likes: 1200,
    comments: 87,
    createdAt: "2025-03-18",
  },
  {
    id: "fallback-6",
    title: "Jazz Horizons",
    artistId: "fallback-artist-5",
    artistName: "Blue Note Sessions",
    coverImage: makeArt("jazz saxophone bar", 106),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    duration: 324,
    genre: "Jazz",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 5400,
    likes: 380,
    comments: 22,
    createdAt: "2025-03-20",
  },
  {
    id: "fallback-7",
    title: "Velocity",
    artistId: "fallback-artist-2",
    artistName: "Neon Architects",
    coverImage: makeArt("speed racing neon", 107),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    duration: 363,
    genre: "Electronic",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 11200,
    likes: 820,
    comments: 54,
    createdAt: "2025-03-22",
  },
  {
    id: "fallback-8",
    title: "Serene Valley",
    artistId: "fallback-artist-3",
    artistName: "Aqua Tones",
    coverImage: makeArt("mountain valley serene", 108),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    duration: 289,
    genre: "Folk",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 4300,
    likes: 290,
    comments: 11,
    createdAt: "2025-04-01",
  },
  {
    id: "fallback-9",
    title: "Deep Space",
    artistId: "fallback-artist-6",
    artistName: "Cosmos Audio Lab",
    coverImage: makeArt("deep space nebula", 109),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    duration: 412,
    genre: "Ambient",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 8900,
    likes: 640,
    comments: 35,
    createdAt: "2025-04-05",
  },
  {
    id: "fallback-10",
    title: "Indie Morning",
    artistId: "fallback-artist-7",
    artistName: "Sunrise Collective",
    coverImage: makeArt("sunrise morning indie", 110),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    duration: 305,
    genre: "Indie",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 6700,
    likes: 450,
    comments: 27,
    createdAt: "2025-04-08",
  },
  {
    id: "fallback-11",
    title: "Pop Groove",
    artistId: "fallback-artist-8",
    artistName: "Studio 11",
    coverImage: makeArt("colorful pop studio", 111),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    duration: 278,
    genre: "Pop",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 13800,
    likes: 1050,
    comments: 68,
    createdAt: "2025-04-10",
  },
  {
    id: "fallback-12",
    title: "Classic Suite",
    artistId: "fallback-artist-9",
    artistName: "Orbital Symphony",
    coverImage: makeArt("classical orchestra concert", 112),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    duration: 451,
    genre: "Classical",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 3900,
    likes: 270,
    comments: 14,
    createdAt: "2025-04-12",
  },
  {
    id: "fallback-13",
    title: "Acoustic Soul",
    artistId: "fallback-artist-7",
    artistName: "Sunrise Collective",
    coverImage: makeArt("acoustic guitar warm", 113),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    duration: 319,
    genre: "Acoustic",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 5200,
    likes: 370,
    comments: 20,
    createdAt: "2025-04-15",
  },
  {
    id: "fallback-14",
    title: "Neon Boulevard",
    artistId: "fallback-artist-2",
    artistName: "Neon Architects",
    coverImage: makeArt("neon boulevard night", 114),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    duration: 345,
    genre: "Electronic",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 10100,
    likes: 750,
    comments: 42,
    createdAt: "2025-04-18",
  },
  {
    id: "fallback-15",
    title: "Summer Breeze",
    artistId: "fallback-artist-8",
    artistName: "Studio 11",
    coverImage: makeArt("summer beach breeze", 115),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    duration: 268,
    genre: "Pop",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 17200,
    likes: 1380,
    comments: 95,
    createdAt: "2025-04-20",
  },
  {
    id: "fallback-16",
    title: "Thunder Ridge",
    artistId: "fallback-artist-4",
    artistName: "Electric Storm",
    coverImage: makeArt("thunder lightning storm", 116),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3",
    duration: 332,
    genre: "Rock",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 14400,
    likes: 1100,
    comments: 76,
    createdAt: "2025-04-22",
  },
  {
    id: "fallback-17",
    title: "Cosmic Drift",
    artistId: "fallback-artist-6",
    artistName: "Cosmos Audio Lab",
    coverImage: makeArt("cosmos drift galaxy", 117),
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-17.mp3",
    duration: 388,
    genre: "Ambient",
    quality: "MP3",
    bitrate: 128,
    sampleRate: 44100,
    playCount: 7300,
    likes: 510,
    comments: 29,
    createdAt: "2025-04-25",
  },
  {
    id: "fallback-18",
    title: "Remy Heart – Don't Let Me Go",
    artistId: "fallback-artist-10",
    artistName: "Phuture Collective",
    coverImage: makeArt("ethereal dreamy synth", 118),
    // Live Audius trending track (verified CORS=* above)
    audioUrl: "https://api.audius.co/v1/tracks/42p38jd/stream?app_name=LAYAM_MUSIC_PLAYER",
    duration: 232,
    genre: "Electronic",
    quality: "MP3",
    bitrate: 320,
    sampleRate: 44100,
    playCount: 28000,
    likes: 2100,
    comments: 145,
    createdAt: "2025-05-01",
  },
  {
    id: "fallback-19",
    title: "MAAD WEST – NEED 2",
    artistId: "fallback-artist-11",
    artistName: "MAAD WEST",
    coverImage: makeArt("hip hop street urban", 119),
    // Live Audius trending track (verified CORS=* above)
    audioUrl: "https://api.audius.co/v1/tracks/9Rg25Qo/stream?app_name=LAYAM_MUSIC_PLAYER",
    duration: 195,
    genre: "Hip-Hop",
    quality: "MP3",
    bitrate: 320,
    sampleRate: 44100,
    playCount: 19500,
    likes: 1650,
    comments: 112,
    createdAt: "2025-05-05",
  },
  {
    id: "fallback-20",
    title: "PATAYA – Slow Down",
    artistId: "fallback-artist-12",
    artistName: "Aspire Higher",
    coverImage: makeArt("chill lofi bedroom", 120),
    // Live Audius trending track (verified CORS=* above)
    audioUrl: "https://api.audius.co/v1/tracks/43kEgzy/stream?app_name=LAYAM_MUSIC_PLAYER",
    duration: 213,
    genre: "Pop",
    quality: "MP3",
    bitrate: 320,
    sampleRate: 44100,
    playCount: 23100,
    likes: 1820,
    comments: 130,
    createdAt: "2025-05-08",
  },
];

export const FALLBACK_ARTISTS: Artist[] = [
  { id: "fallback-artist-1",  name: "SoundHelix Collective", handle: "@soundhelix",  avatar: makeArt("music producer studio", 201), bio: "Royalty-free music for creators.",         followers: 8200,  verified: true },
  { id: "fallback-artist-2",  name: "Neon Architects",       handle: "@neonarch",    avatar: makeArt("neon geometric art",    202), bio: "Electronic and synthwave producers.",    followers: 12400, verified: true },
  { id: "fallback-artist-3",  name: "Aqua Tones",            handle: "@aquatones",   avatar: makeArt("water reflection",      203), bio: "Ambient soundscapes and folk.",          followers: 5600,  verified: false },
  { id: "fallback-artist-4",  name: "Electric Storm",        handle: "@elecstorm",   avatar: makeArt("lightning guitar",      204), bio: "Hard rock and alternative.",             followers: 21000, verified: true },
  { id: "fallback-artist-5",  name: "Blue Note Sessions",    handle: "@bluenote",    avatar: makeArt("jazz piano night",      205), bio: "Live jazz and soul recordings.",         followers: 4300,  verified: false },
  { id: "fallback-artist-6",  name: "Cosmos Audio Lab",      handle: "@cosmosaudio", avatar: makeArt("space telescope",       206), bio: "Ambient and electronic space music.",    followers: 9100,  verified: true },
  { id: "fallback-artist-7",  name: "Sunrise Collective",    handle: "@sunrise",     avatar: makeArt("sunrise landscape",     207), bio: "Indie and acoustic compositions.",       followers: 7800,  verified: false },
  { id: "fallback-artist-8",  name: "Studio 11",             handle: "@studio11",    avatar: makeArt("recording studio",      208), bio: "Pop productions and grooves.",           followers: 16500, verified: true },
  { id: "fallback-artist-9",  name: "Orbital Symphony",      handle: "@orbital",     avatar: makeArt("orchestra conductor",   209), bio: "Classical and contemporary compositions.",followers: 3200, verified: false },
  { id: "fallback-artist-10", name: "Phuture Collective",    handle: "@phuture",     avatar: makeArt("future bass synth",     210), bio: "Future bass and electronic pop.",       followers: 34000, verified: true },
  { id: "fallback-artist-11", name: "MAAD WEST",             handle: "@maadwest",    avatar: makeArt("hip hop street art",    211), bio: "West coast hip-hop and rap.",           followers: 27000, verified: true },
  { id: "fallback-artist-12", name: "Aspire Higher",         handle: "@aspirehigher",avatar: makeArt("motivational sky",     212), bio: "Chill pop and lo-fi beats.",             followers: 41000, verified: true },
];
